# ==============================================================================
# File: 09_plantviroml_ppv_dashboard.py
# Description: PlantViroML-PPV Genomic Intelligence Dashboard (Streamlit)
#              - Modified to include built-in example sequences (OK562672.1, KF472134.1, KP998124.1)
# ==============================================================================

import os
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

# Streamlit page configuration
st.set_page_config(
    page_title="PlantViroML-PPV Genomic Surveillance",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Load trained models with caching
@st.cache_resource
def load_trained_models():
    models = {}
    target_names = ['Strain', 'Country', 'Host', 'Recombinant', 'Mutation_Status']
    for name in target_names:
        model_filename = f'plantviroml_ppv_{name}_rf_model.pkl'
        if os.path.exists(model_filename):
            try:
                models[name] = joblib.load(model_filename)
            except Exception as e:
                print(f"Error loading {model_filename}: {e}")
    return models

models = load_trained_models()

# Define built-in example sequences from the attached files
@st.cache_data
def get_example_records():
    # Example 1: OK562672.1 Plum pox virus isolate Y3, complete genome
    seq1 = ("AAAATATAAAAACTCAACACAACTTACGAAATTTTATGCGATCAAACAAACTTCAAGCTTTCAAAAACTT"
            "GAATCATTTGCTAACCAATCTGCAAAGCACCCGTACTCTTTGCTCCAATCTTTTTGCTTACAAATCACAC"
            "TTTACGATGTCAACCATTGTATTTGGCTCATTTACTTGTTGTCTTGTCGCAGCAATCCATCAGGATAATG"
            "CGGACAGAGTGGCAAAGGCCTGGGCTCGCCCAGAGAACCGCCAAATCAGTAATGTGCATCTATTGTGCAG"
            "GAGGACTGCAAAAAGTCTCATAAATACATACGAGAGTGCAACAGCTAGCGCCTGGAAAGGGCTAGAGGAG"
            "AAACTTCAACCAATGTTTGCTAAGCGAGAGTTTAGCAAAACAATTACGAAACGGAAAGGGCTTCGATGCT"
            "TCAAGGCAAGTTCGGAGCAAGTCATTGAGAGGAAACTCAAGCAGCAATACAAGGAGGAACGCGAGCGGTT"
            "CCAATGGATCAACGGGCCCGAGAATGTGGTAACCCACATCGAGCCAGTTACTGAAGAGGCTCCAACTTGG"
            "GTACCTTTTCCTGATGTCCCTAAGAGACCTCTCTCTAGAACACCTTCAATGAAGAGGCACATCATCTTTG"
            "ACAAGGTCAGGATGTCTGAGACCACTCTGCAGTTATTCATGCGGAAAGTAGCCAACAACGCAAAGGCGAA"
            "CGGGCAGAAGGTCGAGATAATAGGCACAAAACATGTAGTTGGAAGCTACATTCGGAAGAGCCAGCTGACA"
            "TATTTCCGCACGCATGTGCGGCATCTAGATGGTCTCAAGCCACGCTACGACATCACTTTGGATGAAGCTA"
            "CAAAGAAGATTGTTCAGATCTTCGCCAATACAAGTGGCTTCAAACATGTTCATAGCAAGGGTGAGATAAC"
            "CCCAGGGATGAGCGGTTTTGTTATAAATCCACGGAACATATCAGATCCAATGCAGATTCACGACACTGAT"
            "CTGTTCATAGTGCGTGGAAAACACAACTCAATCCTCGTTGACGCACGTTGCCCGGTCTCTAAGGAGCATA"
            "GCAACGAGTTAGTCCACTACTCAGACCCAGGCAAGAAGTTTTGGGTGGGATTCACGAATTCATTTGCTCA"
            "ATGTAAATTGCGTGAGACTGACCATCAATGCACGTCTGACTTAGATGTGCAAGAGTGTGGATATGTTGCG"
            "GCACTTGTTTGCCAGGCTATCATTCCGTGTGGGAAGATCACATGCCTGCAATGTGCGGAGAAGTATGCAT"
            "ACATGTCACAGCAAGAGATCCGTGATAGATTCTCTACGGTCATTGAGCAACATGAGAAAACAGTGATGGA"
            "TAGCTACCCGCAATTTTCACATGTGCTTGCGTTCCTCAAGAGATATCGTGAATTAATGCGGGTTGAGAAT"
            "CAAAATTATGAGGCATTCAAAGATATCACTCACATGATTGGTGAGCGTAAAGAAGCACCATTCTCCCACA"
            "TTAACAAAATTAATGAATTGATCATCAAGGGTGGAATGATGACTGTGCAAGATTACTCAGAAGCTTCAGA"
            "TCGCTTGCGAGAACTCGCACGTTACCAGAAAAATCGAACGGAGAACATTCAGAGTGGCTCCATAAAGGCT"
            "TTCAGAAATAAAATCTCCGCCAAAGCACATGTCAACATGCAACTCATGTGTGACAACCAGCTTGATACTA"
            "ATGGTAATTTTGTGTGGGGTCAAAGGGAGTATCATGCCAAGCGCTTCTTTCGGAACTATTTCAATGTGAT"
            "AGACACAAGTGAGGGGTACAGGCGACACATTGTTCGTGAGAACCCAAGGGGAACTCGTAAGCTGGCAATA"
            "GGGAACCTCGTTATGTCCACCAACCTGGCTGCGTTGCGCAAGCAATTACTTGGTGAGGAGTGCAATCGCT"
            "TTGAAGTATCCAAAGAATGCACAAGCAAGCGAGGTGCGAACTTTGTCTACCAATGTTGCTGTGTCACACA"
            "TGAGGACGGCACACCATTGGAATCTGAGATCATAAGCCCAACAAAGAATCATTTGGTAATTGGCAATTCA"
            "GGGGATTCAAAGTACGTTGACTTACCAAAGACAGAAGGGGGTGGAATGTACATCGCAAAGGCAGGCTATT"
            "GCTACATCAACATATTTCTTGCGATGCTCGTTAATGTTAATGAAGGTGAAGCAAAGAGTTTCACGAAGAC"
            "TGTGCGAGACACACTGGTACCTAAGCTCGGAACATGGCCATCCATGATGGATTTAGCAACAGCATGTCAC"
            "TTTCTTGCAGTGCTATATCCGGAGACTAGAAACGCTGAACTCCCAAGGATACTTGTTGATCACGAATCAA"
            "AGATATTTCATGTCGTTGATTCGTATGGTTCATTATCGACGGGCATGCACATCCTGAAAGCAAACACAGT"
            "GAACCAACTTATAAGCTTTGCAAGTGACACGCTAGACTCAAGCATGAAAATGTATCTCGTTGGAGGTCTA"
            "GAGGTTGATCGATGCGATGAATTCAAGAATGTGAAACTCCTCATCCGGAGTATTTATAGACCAGAGTTAA"
            "TGCAACAAGTGCTGACTGAAGAGCCATATTTACTGATTATGAGCGTATTGTCGCCTGGTGTTCTGATGGC"
            "ATTGTTTAATAGTGGTTCACTCGAAAAAGCAACTCAGTACTGGATAACACGATCGCACAGTCTAGCAGCT"
            "ATAGTGTCAATGCTATCAGCCTTGGCTGCGAAAGTTTCACTAGCGCAAACTCTGAATGCCCAGATGAACG"
            "TTATAGATGAGCATGCATCAGTCCTCCACGATAGTGTTTTCAACGGGACAAAGCCTTATGCATCTTACAT"
            "AATGGCAATTAAAACACTAGAACGAATGAAGGCACGAACTGAATCAGATCACACACTGCATGACTTGGGC"
            "TTCTCCGTGTTACGGAATGCAACACCCCACTTGGTAGAAAAAAGTTATCTACAGGAGTTAGAGCAAGCCT"
            "GGAAAGAACTAAGTTGGTCGGAAAGATTCTCTGCAATGTTGGAATCACAGCGGTGGCGAAGACATATACC"
            "AAGACCTTTTGTCCCAGCCGCTTCAGCAGATTTAGGCGGCAGATACGACATCTCACTTCGGTCATTACTT"
            "GGCAGCCAGTACAAACGCCTGAAAGGGGGAATAAGACGAAAGAAGAACAGCGTAGTATGTTATGCACACC"
            "AGTCAATGGGGAAGCTATTCTGCAAAGCTGTCGGTCTTTCAACGAATTTTCTTCCAAAAGCTTTCAAGAT"
            "GATTGATATGCTAATTGTGATCAGTCTTCTCTTGACTATCGGTGCCACATGCAAATCCATGATCAATGAG"
            "CATCAGCAGCTTAAACAGATGGCTGTCGATCGTGAGACCAATAAGAGGTTCAAGCGCTTACAGCTTTTGT"
            "ATGCGTGGGTTACGGACAAACTTGGTTATATGCCAACAGCAGAGGAGTTCTTGGAATATGTGCAAGGGGA"
            "AAACCCTGAACTAGTTAAATATGCTGAGGACCTTATTGGAGAGGGTCAGGTTGTAGTCCATCAAAGCAAG"
            "AGGGAGTCCCAAGCAAATCTTGAACGAGTGGTGGCATTTGTCGCACTCGTGATGATGTTATTTGATTCAG"
            "AGAGGAGTGATGGCGTATACAAGATTTTGACCAAGCTCAAAGGTATCATGGGGAGCATTGATCAAACAGT"
            "GCATCATCAGAGTTTAGATGACATTGAGGATATTTTGGACGAGAAGAAGCTAACAGTTGATTTTGTTTTG"
            "CAAAGTAATGAGGTTGCACCAACAGTTCCTTTTGACTCAACATTCGAAAAGTGGTGGACGAATCAACTCG"
            "AAACAGGAAACGTCGTACCACACTACCGGACTGAAGGTCATTTCATGGAATTCACAAGGGAAAATGCAGC"
            "ACATGTTGCAAACGAAGTGATGCATGGTCCACACATGGACATTCTGATCAGGGGTGCTGTTGGATCAGGC"
            "AAATCTACTGGGCTACCATTTCACTTGAGCAAAAAGGGTCATGTCCTCTTACTTGAACCAACTCGACCAT"
            "TGGCTGAGAATGTATGTAAACAGTTGCGAGGACAACCTTTCAATGTTAACCCCACATTGCGCATGCGAGG"
            "CTTGAGCACTTTTGGCTCAACCCCGATCACTGTGATGACAAGTGGATATGCACTGCACTTTCTTGCAAAT"
            "AATCCAGTTTACCTGGATAACTATAAATGCATCATTTTTGACGAGTGCCACGTTCATGACGCATCAGCAA"
            "TGGCAGTTAGATGTCTGTTATCGGAATACTCCTATCCAGGGAAAATTCTGAAAGTCTCAGCGACACCCCC"
            "TGGGCATGAGGTGGATTTCAAGACACAAAAGGAAGTCAAGGTCATTGTCGAAGAATCATTGTCATTCCAA"
            "CAATTCGTGTCAAATCTTGGGTCTGGTTGCAACAGTGATATCTTGAAATATGGCGCAAACATACTTGTGT"
            "ACGTAGCAAGTTATAATGAAGTTGACACACTTGGAAAGCTTCTCACAGATAGGAACTTCAAGGTCTCAAA"
            "GGTTGATGGTCGCACCATGAAAGTTGGGAGTGTGGAAATACCAACGAGCGGTACGCAAGCTAAGCCACAT"
            "TTCGTGGTCGCCACAAACATTATTGAAAATGGTGTCACATTGGATATAGATGTTGTTGTCGACTTCGGGT"
            "TGAAAGTGGTCCCTGTTCTAGACGTTGATAATCGACTTGTGCGGTATAAAAAGACAAATATCAGTTATGG"
            "CGAGCGGATTCAGCGGCTCGGTCGTGTTGGTCGAAACAAACCAGGCGCAGCATTGCGAATTGGATTCACA"
            "GAGAAAGGTTTAACCCAGATTCCACCAATGATTGCAACTGAGGCCGCTTTCTTGTGCTTCACATATGGTC"
            "TCCCTGTCATGACAAATGGTGTATCGACAAGCCTTCTCGCGATGTGCACGGTGAAGCAGGCACGAACTAT"
            "GCAGCAGTTCGAACTGTCCCCTTTCTACACAGCAGCTATGGTCAGGTTTGACGGTACAATGCATCAGGAA"
            "ATTTTTCGACTGTTGAAGAGTTACAGGTTGCGGGACTCAGAAGTGATCTTGAATAAGTTGGCCATACCAA"
            "ATGGCAATGTTGGTGGGTGGATGAGCGTGCGAGATTACAAGCGGCAAGGCTGTAATTTGGATCTTGACGA"
            "CAATGTTCGGATTCCATTCTACGTCAAAGATTTGCCTGAGCTTTTGCATGAACAGATATGGCAAGCGGTC"
            "GAGAATTACAAATCGGATGCTGGCTTTGGTAGGATTTGTAGCTCTAGTGCTTGCAAAATAGCCTACACGC"
            "TGCAGACGGACATACACTCCATCCCACGAACTGTCAAAATCATTGATGTATTGTTGGAACAAGAGCGGAC"
            "GAAACAGGCTCATTTTAGGGCTATGACAAGTCAATCATGCTCAAGTTCAAATTTCTCCTTGTCCAGTATC"
            "ACATCAGCTATCCGATCGAAGTACGCGAAAGATCATACAGAGGAGAATATTGGAGTGCTTCAAATGGCAA"
            "AGGCGCAACTCTTAGAGTTCCAAAACTTGAACATTGATCCAAGCTATCCCGAACTTGTGCGCAACTTTGG"
            "TGCACTAGAATGTGTGCATCACCAGACAAAGGAAGGAGTTTCCAACACCTTGAAGCTCAAGGGACACTGG"
            "AACAAGCAACTTGTAACACGTGATGCAACCTTGATGCTGGGGGTGGTTGGTGGTGGAGCATGGATGATTT"
            "ACAGCTATCTGAAGGACAGCTTCAAAGAAGAAGTTGCTCACCAAGGGTTCAATCGACGGCAGAGACAAAA"
            "ACTTAAGTTTCGTCAAGCTCGTGATAACCGGATGGCTCGAGAAGTGTATGGAGATGATTCCACGATGGAA"
            "GAATATTTTGGTTCAGCATACTCAAAGAAGGGCAAAAGCAAGGGTCGGACCAGAGGCATGGGCACCAAGA"
            "CGAGAAAGTTCGTGAATATGTATGGTTACGATCCTACAGACTACAACTTTGTTCGCTTTGTGGATCCGTT"
            "GACTGGGCATACACTCGATGAGAATCCTCTCATGGATATAGGTTTGGTGCAGGAACACTTCTCTATAATT"
            "CGGAATGAGCAAATTGGAGATGACAAGATCACACCACAACACATAATGGCTAACCCTGGACTTGTGGCAT"
            "ACTACGTCAAGGATGCAACTCAAAAGGCTCTCAAGATTGATCTTACGCCTCACAATCCATTACGAGTTTG"
            "TGATAAAACTGCTACAATAGCAGGTTTTCCGGAGAGAGAGTTCGAGTTGAGACAAACAGGACAGCCAACT"
            "TTCGTCGAACCCAGCGCTGTGCCAAAGGCAAATGAGGTTGAGAGTGAGGAAGTCGATCATGAAAGCAAGT"
            "CACTGTTTAGAGGTTTGAGGGACTACAATCCAATTGCGAGCTCAATATGCCAGCTGACGAATTCATCAGG"
            "TGCCCGAAACAGTGAAATGTTTGGTTTGGGATTTGGAGGCGTGATCATTACAAATCAACATTTGTTTAAG"
            "AGGAATGACGGAGAGTTGACAATTCGATCACACCACGGTGAGTTTGTTGTCAGGGACACGAAAACACTCA"
            "AATTGCTGCCTTGCAAGGGTCGGGACATCGTGATCATCAGACTGCCAAAGGACTTTCCCCCTTTTCCGAA"
            "GAGGTTGCAATTCAGGACACCTACAACTGAGGACAGGGTTTGCTTGATTGGGTCAAATTTCCAAACAAGA"
            "AGTATCTCAAGCACAATGTCTGAAACAAGTGCAACGTATCCTGTTGATAATAGTCACTTTTGGAAACACT"
            "GGATCAGCACGAAAGACGGGCATTGTGGACTGCCCATTGTAAGCACAAGGGATGGAAACATCCTTGGATT"
            "GCACAGCCTGGCAAATTCAACCAATACGCAAAATTTCTATGCGGCATTTCCTGAGAACTTTGAAGTGGAC"
            "TATTATTTGTCGAACAACGATGCCGCGAATTGGATTAAGCAATGGAGATACAATCCAGATGAAGTTTGTT"
            "GGGGTTCCCTACAACTCAAGAGAGATGTTCCCCAAAGTCCTTTCAAAATTTGCAAGTTACTCACGGATCT"
            "CGAGGGGGATACAGTCTATACTCAATCCAAGACAACGCACTGGTTACGCGACAAGCTGGAAGGCAATTTG"
            "AAGGCGGTTGGAGCCTGTCCAGGACAACTGGTTACGAAGCACGTAGTGAAGGGAAAGTGCACACTGTTCG"
            "AAACCTACTTGCTGACACACCCAGATGAGCGTGCATTTTTCCAGCCGTTGATGGGGGCCTATCAGAAAAG"
            "TGCTCTAAATAAGGATGCCTACGTAAAGGATCTGATGAAGTATTCCAAGCCCATAGTTGTTGGGACTGTC"
            "GATTGCGAGCAATTTGAGCGTGCGGTGAATGCGGTCATTTCAATGTTGATTTCAAAAGGTTTTGAGGAGT"
            "GTTGTTACGTTACAGATCCAGATGACATATTCGCAGCACTAAATATGAAGGCAGCAGTTGGGGCACTTTA"
            "CAGTGGGAAGAAAAGAGACTACTTTGAGAATGTGTCTGAAGATGAAAAATATGAATTTGTGCGTGCCAGC"
            "TGTAAACGTCTATTTATGGGGCAGAAAGGAGTCTGGAACGGATCACTCAAAGCTGAGTTGCGACCAAAGG"
            "AGAAAGTCGAAGCTAACAAAACGCGCTCATTCACGGCAGCACCCATTGACACTCTTCTCGGAGGCAAAGT"
            "GTGCGTAGACGACTTCAACAATCAGTTCTACAGCCTGAATTTGCACTGTCCTTGGAGTGTTGGAATGACA"
            "AAATTCAGAGGTGGATGGGACAAGCTGCTAAGGTCGTTGCCAGACGGCTGGATTTACTGTGATGCGGATG"
            "GCTCACAATTTGATAGCTCCTTGTCACCATATCTCATTAATGCAGTGCTGAACATTCGGTTAGCTTTCAT"
            "GGAAAAATGGGACATTGGTGAACAAATGTTATCCAACTTGTACACCGAGATTGTTTACACACCAATAGCA"
            "ACCCCGGATGGAACCATTGTCAAGAAGTTCAAAGGAAATAATAGTGGACAACCATCCACAGTCGTAGACA"
            "ATACGCTCATGGTCATTCTAGCAATGACATACTCGCTTTTGAAGCTTGGATACCATCCAGACACACACGA"
            "CTGTATTTGCAAGTACTTTGTGAATGGTGATGACTTAGCCATAGCGATTCATCCGTCGCATGAGCACATT"
            "TATGATGAGCTTCAAGAGTTATTTTCCCAGCTCGGATTGAACTATACATTCACAGCGAAAACCGAGAACA"
            "AAGAGGAGCTATGGTTCATGTCTCACAAAGGTGTATTGCATGATGGGATGTACATCCCGAAGTTGGAACC"
            "TGAAAGGATAGTGTCAATACTTGAGTGGGATAGGTCACATGAACCAATTCACAGATTGGAAGCAATTTGT"
            "GCATCGATGGTTGAAGCTTGGGGTTATGGAGATCTGTTGAGGGAAATTCGAAAATTTTATAGCTGGGTTC"
            "TTGAACAGGCACCGTACAATGCCCTGTCGAAAGATGGAAAAGCCCCATACATAGCAGAGACCGCTCTGAA"
            "AAAGTTGTACACAGATGAAGAAGCTTCTGAGACGGAGATTGAAAGGTACCTTGAAGCCTTCTACAACAAT"
            "GCTGGTGATGAGTTTGACTCCAACATAGTGGTTCATCAGGCGAATGAGGGTAACTACGATGACGCAACTT"
            "TGGTGGATGCAGGCAAGTCTACTGTTACTACAGCAGCGTCCACGCCTGTGACAACAAGCTCACAATTACC"
            "ACCCCCGCCATTTCCGAGTTTACAGAGCACAACACCAATGTTCGACCCCATTTTCACTCCAGCAACAACC"
            "CAGCTGAATGTGCGACCAATAGCACCAACGTCGACAAGTCCATTCTCTTACGGAGTGATTGGGAACCAAA"
            "ATGTGACACCTTCCTCTTCGAATGCACTGGTTAACACAAGGAAGGATCGAGACGTCGATGCGGGGACAAT"
            "TGGAACTTTATCCGTACCTCGATTGAAAGCTATGACCTCAAAGCTGTCACTGCCAAAAGTGAAGGGGAAA"
            "GCCATCATGAATCTTAATCATTTAGCTCACTACAACCCTGCGCAGGTTGATCTATCTAACACACGAGCTC"
            "CACAATCTTGCTTCCAAACTTGGTATGAAGGAGTTAAGCGTGACTATGATGTTACGGATGATGAAATGAG"
            "CATTATACTGAATGGGCTTATGGTCTGGTGCATTGAAAATGGAACTTCCCCAAACATCAATGGGATGTGG"
            "GTCATGATGGACGGAGATACACAAGTGGAGTATCCAATAAAGCCATTATTGGATCATGCGAAACCCACTT"
            "TTAGACAAATTATGGCACATTTCAGTAACGTCGCTGAAGCGTATATTGAAAAACGGAATTATGAGAAAGC"
            "ATACATGCCAAGGTATGGTATTCAGCGAAACCTGACGGATTACAGCCTCGCCAGATACGCCTTTGATTTT"
            "TACGAGATGACCTCGACAACGCCTGTTAGGGCACGAGAGGCACACATTCAGATGAAGGCAGCAGCATTGA"
            "GAAATGTTCAAAATCGTTTATTTGGCTTGGATGGAAATGTTGGAACACAAGAAGAGGACACAGAGAGACA"
            "CACCGCTGGTGATGTTAATCGCAACATGCACAACCTCCTCGGTGTGAGGGGAGTGTAGTGGTCTCGGTAT"
            "CTATCATAAACTCTACTTGGGTGAGAGTCTAGTCACCCAACTGTTTTTAGATTCCTGTTAGCATCCTTTT"
            "CTCCGCTTTAATAGCAGTACATTTAGTGAGGTTTTACCTCCATATGTTCTAGTCTGTTATTGTCGAACAC"
            "AGGCCCTTGTATCTGATGTAGCGAGTGCTTCACTCCATTCGGGTTATAGTTCTTGTGCAAGAGAC")

    # Example 2: KF472134.1 Plum pox virus strain Rec, complete genome
    seq2 = ("AAAATATAAAAACTCAACACAACATACAAAATTTTATGCGATCAAATCAATCCCAAGCTATCAAAATTTT"
            "TCAAATCTCACTTGAAAGATCAAAAATCAACAAAGAACATTCCTCAATTTGTCTACCAAATTCACTGCAA"
            "GTCAAGATGTCAACCATTGTATTTGGCTCATTCACTTGCCACCTCGATGCAGCTATCCACCAGGATAATG"
            "CAGACAGATTGGCAAAGGCCTGGACCCGTCCAGAGAACCGCCAAGTCAGTAACGTGCATCTACTGTGCCG"
            "AAGAGCGGCAAAAAGTCTCATAAATACATATGAGAGTGCAACAGCTAGTGCTTGGAAAGGGCTGGAGGAG"
            "AAGTTGCAACCTATGTTTGCTAAGCGAGAGTTTAGCAAAACAGTCACAAAGAGAAAAGGGCTTCGGTGCT"
            "TCAAAGAAAGCTCTGAGAAGTTTATTGAAAAGAAGCTCAGGAAACAGTATCAAGAGGAGCGTGAGAGATT"
            "CCAATTTCTCAACGGTCCAGATGCAATAGTCAACCAAATCAGTGTTGACAAATGTGAAGCT
